// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.1
// source: junctiond/proto/junctiond.proto

package junctiond

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JunctionService_Spawn_FullMethodName  = "/junctiond.JunctionService/Spawn"
	JunctionService_Remove_FullMethodName = "/junctiond.JunctionService/Remove"
	JunctionService_List_FullMethodName   = "/junctiond.JunctionService/List"
)

// JunctionServiceClient is the client API for JunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This defines the public API that Go will call.
// JunctionD runs locally, so Go talks to it over gRPC.
// Exactly mirrors the C++ JunctionD class (spawn, remove, list).
type JunctionServiceClient interface {
	// Create a new instance of a function (maps to JunctionD::spawn)
	Spawn(ctx context.Context, in *FunctionData, opts ...grpc.CallOption) (*StatusReply, error)
	// Stop and remove a running instance (maps to JunctionD::remove)
	Remove(ctx context.Context, in *FunctionName, opts ...grpc.CallOption) (*StatusReply, error)
	// List all currently running instances (maps to JunctionD::list)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FunctionList, error)
}

type junctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJunctionServiceClient(cc grpc.ClientConnInterface) JunctionServiceClient {
	return &junctionServiceClient{cc}
}

func (c *junctionServiceClient) Spawn(ctx context.Context, in *FunctionData, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, JunctionService_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junctionServiceClient) Remove(ctx context.Context, in *FunctionName, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, JunctionService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junctionServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FunctionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunctionList)
	err := c.cc.Invoke(ctx, JunctionService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JunctionServiceServer is the server API for JunctionService service.
// All implementations must embed UnimplementedJunctionServiceServer
// for forward compatibility.
//
// This defines the public API that Go will call.
// JunctionD runs locally, so Go talks to it over gRPC.
// Exactly mirrors the C++ JunctionD class (spawn, remove, list).
type JunctionServiceServer interface {
	// Create a new instance of a function (maps to JunctionD::spawn)
	Spawn(context.Context, *FunctionData) (*StatusReply, error)
	// Stop and remove a running instance (maps to JunctionD::remove)
	Remove(context.Context, *FunctionName) (*StatusReply, error)
	// List all currently running instances (maps to JunctionD::list)
	List(context.Context, *Empty) (*FunctionList, error)
	mustEmbedUnimplementedJunctionServiceServer()
}

// UnimplementedJunctionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJunctionServiceServer struct{}

func (UnimplementedJunctionServiceServer) Spawn(context.Context, *FunctionData) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedJunctionServiceServer) Remove(context.Context, *FunctionName) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedJunctionServiceServer) List(context.Context, *Empty) (*FunctionList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedJunctionServiceServer) mustEmbedUnimplementedJunctionServiceServer() {}
func (UnimplementedJunctionServiceServer) testEmbeddedByValue()                         {}

// UnsafeJunctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JunctionServiceServer will
// result in compilation errors.
type UnsafeJunctionServiceServer interface {
	mustEmbedUnimplementedJunctionServiceServer()
}

func RegisterJunctionServiceServer(s grpc.ServiceRegistrar, srv JunctionServiceServer) {
	// If the following call panics, it indicates UnimplementedJunctionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JunctionService_ServiceDesc, srv)
}

func _JunctionService_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunctionServiceServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JunctionService_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunctionServiceServer).Spawn(ctx, req.(*FunctionData))
	}
	return interceptor(ctx, in, info, handler)
}

func _JunctionService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunctionServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JunctionService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunctionServiceServer).Remove(ctx, req.(*FunctionName))
	}
	return interceptor(ctx, in, info, handler)
}

func _JunctionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunctionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JunctionService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunctionServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// JunctionService_ServiceDesc is the grpc.ServiceDesc for JunctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JunctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "junctiond.JunctionService",
	HandlerType: (*JunctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _JunctionService_Spawn_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _JunctionService_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _JunctionService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "junctiond/proto/junctiond.proto",
}
