// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: junctiond/proto/junctiond.proto

package junctiond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_junctiond_proto_junctiond_proto_rawDescGZIP(), []int{0}
}

type FunctionData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Same fields as your C++ FunctionData struct
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rootfs        string `protobuf:"bytes,2,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	Cpu           int32  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryMB      int32  `protobuf:"varint,4,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	Execpath      string `protobuf:"bytes,5,opt,name=execpath,proto3" json:"execpath,omitempty"`
	Args          string `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionData) Reset() {
	*x = FunctionData{}
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionData) ProtoMessage() {}

func (x *FunctionData) ProtoReflect() protoreflect.Message {
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionData.ProtoReflect.Descriptor instead.
func (*FunctionData) Descriptor() ([]byte, []int) {
	return file_junctiond_proto_junctiond_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionData) GetRootfs() string {
	if x != nil {
		return x.Rootfs
	}
	return ""
}

func (x *FunctionData) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *FunctionData) GetMemoryMB() int32 {
	if x != nil {
		return x.MemoryMB
	}
	return 0
}

func (x *FunctionData) GetExecpath() string {
	if x != nil {
		return x.Execpath
	}
	return ""
}

func (x *FunctionData) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type FunctionName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionName) Reset() {
	*x = FunctionName{}
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionName) ProtoMessage() {}

func (x *FunctionName) ProtoReflect() protoreflect.Message {
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionName.ProtoReflect.Descriptor instead.
func (*FunctionName) Descriptor() ([]byte, []int) {
	return file_junctiond_proto_junctiond_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FunctionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionStatus) Reset() {
	*x = FunctionStatus{}
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionStatus) ProtoMessage() {}

func (x *FunctionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionStatus.ProtoReflect.Descriptor instead.
func (*FunctionStatus) Descriptor() ([]byte, []int) {
	return file_junctiond_proto_junctiond_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *FunctionStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type FunctionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*FunctionStatus      `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionList) Reset() {
	*x = FunctionList{}
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionList) ProtoMessage() {}

func (x *FunctionList) ProtoReflect() protoreflect.Message {
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionList.ProtoReflect.Descriptor instead.
func (*FunctionList) Descriptor() ([]byte, []int) {
	return file_junctiond_proto_junctiond_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionList) GetFunctions() []*FunctionStatus {
	if x != nil {
		return x.Functions
	}
	return nil
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_junctiond_proto_junctiond_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_junctiond_proto_junctiond_proto_rawDescGZIP(), []int{5}
}

func (x *StatusReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_junctiond_proto_junctiond_proto protoreflect.FileDescriptor

const file_junctiond_proto_junctiond_proto_rawDesc = "" +
	"\n" +
	"\x1fjunctiond/proto/junctiond.proto\x12\tjunctiond\"\a\n" +
	"\x05Empty\"\x98\x01\n" +
	"\fFunctionData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06rootfs\x18\x02 \x01(\tR\x06rootfs\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12\x1a\n" +
	"\bmemoryMB\x18\x04 \x01(\x05R\bmemoryMB\x12\x1a\n" +
	"\bexecpath\x18\x05 \x01(\tR\bexecpath\x12\x12\n" +
	"\x04args\x18\x06 \x01(\tR\x04args\"\"\n" +
	"\fFunctionName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"P\n" +
	"\x0eFunctionStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"G\n" +
	"\fFunctionList\x127\n" +
	"\tfunctions\x18\x01 \x03(\v2\x19.junctiond.FunctionStatusR\tfunctions\"A\n" +
	"\vStatusReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb9\x01\n" +
	"\x0fJunctionService\x128\n" +
	"\x05Spawn\x12\x17.junctiond.FunctionData\x1a\x16.junctiond.StatusReply\x129\n" +
	"\x06Remove\x12\x17.junctiond.FunctionName\x1a\x16.junctiond.StatusReply\x121\n" +
	"\x04List\x12\x10.junctiond.Empty\x1a\x17.junctiond.FunctionListB5Z3github.com/DonaldLucy/faasd/pkg/junctiond;junctiondb\x06proto3"

var (
	file_junctiond_proto_junctiond_proto_rawDescOnce sync.Once
	file_junctiond_proto_junctiond_proto_rawDescData []byte
)

func file_junctiond_proto_junctiond_proto_rawDescGZIP() []byte {
	file_junctiond_proto_junctiond_proto_rawDescOnce.Do(func() {
		file_junctiond_proto_junctiond_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_junctiond_proto_junctiond_proto_rawDesc), len(file_junctiond_proto_junctiond_proto_rawDesc)))
	})
	return file_junctiond_proto_junctiond_proto_rawDescData
}

var file_junctiond_proto_junctiond_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_junctiond_proto_junctiond_proto_goTypes = []any{
	(*Empty)(nil),          // 0: junctiond.Empty
	(*FunctionData)(nil),   // 1: junctiond.FunctionData
	(*FunctionName)(nil),   // 2: junctiond.FunctionName
	(*FunctionStatus)(nil), // 3: junctiond.FunctionStatus
	(*FunctionList)(nil),   // 4: junctiond.FunctionList
	(*StatusReply)(nil),    // 5: junctiond.StatusReply
}
var file_junctiond_proto_junctiond_proto_depIdxs = []int32{
	3, // 0: junctiond.FunctionList.functions:type_name -> junctiond.FunctionStatus
	1, // 1: junctiond.JunctionService.Spawn:input_type -> junctiond.FunctionData
	2, // 2: junctiond.JunctionService.Remove:input_type -> junctiond.FunctionName
	0, // 3: junctiond.JunctionService.List:input_type -> junctiond.Empty
	5, // 4: junctiond.JunctionService.Spawn:output_type -> junctiond.StatusReply
	5, // 5: junctiond.JunctionService.Remove:output_type -> junctiond.StatusReply
	4, // 6: junctiond.JunctionService.List:output_type -> junctiond.FunctionList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_junctiond_proto_junctiond_proto_init() }
func file_junctiond_proto_junctiond_proto_init() {
	if File_junctiond_proto_junctiond_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_junctiond_proto_junctiond_proto_rawDesc), len(file_junctiond_proto_junctiond_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_junctiond_proto_junctiond_proto_goTypes,
		DependencyIndexes: file_junctiond_proto_junctiond_proto_depIdxs,
		MessageInfos:      file_junctiond_proto_junctiond_proto_msgTypes,
	}.Build()
	File_junctiond_proto_junctiond_proto = out.File
	file_junctiond_proto_junctiond_proto_goTypes = nil
	file_junctiond_proto_junctiond_proto_depIdxs = nil
}
